// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot.commands.background.drive;
import edu.wpi.first.wpilibj.command.InstantCommand;
import frc.robot.Robot;
import frc.robot.subsystems.*;

/**
 *
 */
public class IntakeSetAsBack extends InstantCommand {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

    // Called once when this command runs
    @Override
    protected void initialize() {
        Robot.logRun(this);
        Robot.drive.setIntakeLocation(Drive.IntakeLocation.BACK);
    }

    @Override
    protected void execute(){
        
    }

    @Override
    protected boolean isFinished(){
        return false;
    }

    @Override
    protected void end(){
        Robot.logEnd(this);
    }

    @Override
    protected void interrupted(){
    }
}
