// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot.commands.scoring.ballmechanism;

import edu.wpi.first.wpilibj.command.Command;
import frc.robot.Robot;
import frc.robot.subsystems.BallStorage.RollerDirection;
//fix pathway

/**
 *
 */
public class IntakeTube extends Command {
    /*
     * - rotate intake wheels (4?) - 1 motor, inverted directions - rotate
     * perpendicular bands (3) - 2 motors, 2 directions - rotate parallel bands (2)
     * - 1 motor, inverted directions
     */
    private double speed;
    // change to more appropriate speed

    public IntakeTube(double speed) {
        requires(Robot.ballStorage);
        this.speed = speed;
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
        Robot.logInitialize(this);
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
        // sequential order
        // rollers, intakeLeft/Right, intakeParallel
        Robot.ballStorage.intakeMain(speed, RollerDirection.INTAKE);
        // Robot.intake.intakeRightLeft(speed, RollerDirection.INTAKE);
        // Robot.intake.intakeParallelBand(speed, RollerDirection.INTAKE);
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    @Override
    protected void interrupted() {
        Robot.logInterrupted(this);
        Robot.ballStorage.intakeMain(0, RollerDirection.INTAKE);
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void end() {
        Robot.logEnd(this);
        Robot.ballStorage.intakeMain(0, RollerDirection.INTAKE);
    }
}
