// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot.commands.scoring.arm;

import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.controller.PIDController;
import frc.robot.Robot;

/**
 *
 */
public class ArmToAngle extends Command {
    private double angle;
    private static double beginningPosition;

    public ArmToAngle(double angle) {
        requires(Robot.drive);
        angle = this.angle;
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
        // Calls to the subsystem to update the angle if controller value has changed
        double time = timeSinceInitialized();
        double speed; 
        double difference = angle - Robot.arm.getArmAngle();
        // Sets the minimum and maximum speed of the robot during the command
        if (time < 1) {
            speed = Math.copySign(time, difference);
        } else if (Math.abs(difference) <= 0.5) {
            speed = 0;
        } else if (Math.abs(difference) < 5) {
            speed = difference * 0.2;
        } else if (Math.abs(difference) > 5) {
            speed = Math.copySign(1, difference);
        } else {
            speed = 0;
        }

        Robot.arm.setArmSpeed(-speed);
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        // asking the pid loop have we reached our position
        return Math.abs(angle - Robot.arm.getArmAngle()) < 0.5;
    }

    @Override
    protected void interrupted() {
        Robot.logInterrupted(this);
        // call the drive subsystem to make sure the PID loop is disabled
        Robot.arm.setArmSpeed(0);
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
        Robot.logEnd(this);
        // call the drive subsystem to make sure the PID loop is disabled
        Robot.arm.setArmSpeed(0);
    }

}