// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot.commands.scoring.arm;

import edu.wpi.first.wpilibj.command.CommandGroup;
import frc.robot.Robot;
import frc.robot.commands.DriveForDistance;
import frc.robot.commands.background.wait.WaitForever;
import frc.robot.commands.scoring.flywheel.FlywheelFullSpeed;
import frc.robot.subsystems.Arm;
import frc.robot.subsystems.Flywheel.FlywheelStates;

/**
 *
 */
public class ArmToShoot extends CommandGroup {

    public ArmToShoot(double angle) {

        if(angle == Arm.towerAngle) {
            addSequential(new DriveForDistance(-5.0/12));
        }
        addParallel(new FlywheelFullSpeed(FlywheelStates.FULL));
        addSequential(new ArmToAngle(angle));
        addSequential(new WaitForever());
    }

    @Override
    protected void initialize() {
        Robot.logInitialize(this);
    }

    @Override
    protected void end() {
        Robot.logEnd(this);
        Robot.flywheel.setFlywheelSpeedState(FlywheelStates.STOP);
    }
}