// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot.commands.autonomous.autoCommands;

import edu.wpi.first.wpilibj.command.WaitCommand;
import frc.robot.commands.autonomous.*;
import frc.robot.commands.autonomous.autoCommands.Enums.*;
import frc.robot.commands.scoring.flywheel.SetFlywheelSpeed;
import frc.robot.subsystems.Flywheel.FlywheelStates;

/**
 *
 */
public class AutoCommand extends AbstractAutoCommand {

    public AutoCommand(AutoOptions auto, StartingPosition start, double waitTime) {

        addSequential(new WaitCommand(waitTime));
        addParallel(new AutonomousRobotPrep());
        if (auto == AutoOptions.SCORE) {      
            addSequential(new SetFlywheelSpeed(FlywheelStates.HALF));
            addSequential(new AutoScore(start));
        }
        if (start == StartingPosition.PUSH_ALLIANCE_MEMBER) {
            addSequential(new DriveForDistance(-1));
            addSequential(new DriveForDistance(2));
        } else {
            addSequential(new DriveForDistance(-1));
        }
        addSequential(new AutonomousFinish());
    }

    @Override
    protected void initialize() {
        super.initialize();
        new AutonomousWatchDog(this).start();//Makes sure that if the robot is in danger of falling over, autonomous gets canceled
    }
}
