// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot.commands.autonomous.autoCommands;

import frc.robot.commands.autonomous.AutonomousFinish;
import frc.robot.commands.autonomous.autoCommands.Enums.StartingPosition;

/**
 *
 */
public class OverrideAuto extends AbstractAutoCommand {

    OverrideAuto(StartingPosition start) {

        addSequential(new AutoScore(start));
        if (start == StartingPosition.PUSH_ALLIANCE_MEMBER) {
            addSequential(new DriveForDistance(-5));
        }
        addSequential(new AutonomousFinish());
        
    }
}

