// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot.commands.autonomous;

import edu.wpi.first.wpilibj.command.CommandGroup;
import frc.robot.Robot;
import frc.robot.commands.scoring.arm.CalibrateArmEncoder;

/**
 *
 */
public class AutonomousFinish extends CommandGroup {

    public AutonomousFinish() {
        addSequential(new CalibrateArmEncoder(false));
    }

    @Override
    protected void initialize() {
        Robot.log("RobotPrep has started");
    }

    @Override
    protected void end() {
        Robot.log("RobotPrep has ended");
    }
}
