// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot.commands.autonomous;

import edu.wpi.first.wpilibj.command.Command;
import frc.robot.Robot;

/**
 *
 */
public class AutonomousWatchDog extends Command {
    private final Command autonomous;

    public AutonomousWatchDog(Command autonomous) {
        this.autonomous = autonomous;
    }

    @Override
    protected void execute() {
        if (Robot.abortAuto()) {
            autonomous.cancel();
        }
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        return !autonomous.isRunning();
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
        Robot.drive.arcadeDrive(0, 0);
        Robot.arm.setArmSpeed(0);
        Robot.intake.controlFeeder(0);
        Robot.lift.resetLiftSolenoid();
        Robot.log("Autonomous Terminated");
    }

}
