// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot.commands;

import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.controller.PIDController;
import frc.robot.Robot;

/**
 *
 */
public class ArmToAngle extends Command {
    private double height;
    private PIDController rotatePID;
    //using the Ziegler-Nichols PID Control Tuning method, we find the proper numbers for the PID loop.
    private static final double Kc = 0.08;
    private static final double Pc = 0.291666;  // period of oscillation (found from average devided by 1/8 of a second(slow mo' camera))
    private static final double P = 0.6 * Kc; 
    private static final double I = 2 * P * 0.05 / Pc;
    private static final double D = 0.125 * P * Pc / 0.05;

    public ArmToAngle(double angle) {
        requires(Robot.drive);
        height = Robot.arm.toHeightInches(angle);
    }

    // Called just before this Command runs the first time
    protected void initialize() {
        /* Make a call to the subsystem to use a PID loop controller in the subsystem
        to set the heading based on the HAT controller. */
        rotatePID = new PIDController(0.5, 0, 0);//P, I, D); //<-- tuned from testing
        rotatePID.setSetpoint(height);
        rotatePID.setTolerance(0.1);
        rotatePID.enableContinuousInput(2, 12);

    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
        // Calls to the subsystem to update the angle if controller value has changed
        double value = rotatePID.calculate(Robot.arm.getArmPosition());
       // Sets the minimum and maximum speed of the robot during the command 
       if (value > 0.5) {
           value = 0.5;
       } else if (value < -0.5) {
           value = -0.5;
       }
       Robot.arm.setArmSpeed(-value);
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        // asking the pid loop have we reached our position
        return rotatePID.atSetpoint();
    }

    @Override
    protected void interrupted() {
        // call the drive subsystem to make sure the PID loop is disabled
        end();
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
        // call the drive subsystem to make sure the PID loop is disabled
        Robot.arm.setArmSpeed(0);
    }

}