// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot.commands;

import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.controller.PIDController;
import frc.robot.Robot;

/**
 *
 */
public class ArmToAngle extends Command {
    private double height;
    private PIDController rotatePID;

    public ArmToAngle(double angle) {
        requires(Robot.drive);
        height = Robot.arm.toHeightInches(angle);
    }

    // Called just before this Command runs the first time
    protected void initialize() {
        rotatePID = new PIDController(0.5, 0, 0);
        rotatePID.setSetpoint(height);
        rotatePID.setTolerance(0.1);
        rotatePID.enableContinuousInput(2, 12);
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
        // Calls to the subsystem to update the angle if controller value has changed
        double value = rotatePID.calculate(Robot.arm.getArmPosition());
        // Sets the minimum and maximum speed of the robot during the command
        if (value > 0.5) {
            value = 0.5;
        } else if (value < -0.3) {
            value = -0.3;
        } else if (value > 0.05) {
            value = 0.05;
        } else if (value < -0.05) {
            value = -0.05;
        }
        Robot.arm.setArmSpeed(-value);
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        // asking the pid loop have we reached our position
        return rotatePID.atSetpoint();
    }

    @Override
    protected void interrupted() {
        // call the drive subsystem to make sure the PID loop is disabled
        end();
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
        // call the drive subsystem to make sure the PID loop is disabled
        Robot.arm.setArmSpeed(0);
    }

}