// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot.commands;

import edu.wpi.first.wpilibj.command.Command;
import frc.robot.Robot;


/**
 *
 */
public class WaitUntilNavXDetected extends Command {

    @Override
    protected void initialize() {
        Robot.logInitialize(this);
    }

    @Override
    protected boolean isFinished() {
        return Robot.isNavXReady();
    }

    @Override
    protected void end() {
        Robot.logEnd(this);
    }
}
